### PR TITLE
Monster should not be nested under character

### PR DESCRIPTION
**Pull request by siegfault**
Pulling it out one level, adding affinities seems to work now.

### CODE REVIEW

**Review by AllPurposeName — APPROVED** [review]

**Comment by mbenfowler** [comment]
wow haha

**Comment by mbenfowler** [comment]
@siegfault so where do these monster attributes now show up in it's `this.actor`?

**Comment by siegfault** [comment]
Yup, exactly!

**Comment by mbenfowler** [comment]
no, WHERE can I find these fields in the console?

**Pull request merged**
